import { CoreError } from './core-error'

export enum AuthErrorCode {
  // Create Account
  INVALID_NICKNAME = 'INVALID_NICKNAME',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  NOT_INVALID_EMAIL = 'NOT_INVALID_EMAIL',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  PASSWORD_IS_SHORT = 'PASSWORD_IS_SHORT',

  // Login
  NOT_REGISTERED_EMAIL = 'NOT_REGISTERED_EMAIL',
  NOT_MATCHED_PASSWORD = 'NOT_MATCHED_PASSWORD',

  // Refresh
  REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING',
  NOT_MATCHED_JTI = 'NOT_MATCHED_JTI',
}

export class AuthError extends CoreError {}
