export enum UserErrorCode {
  // Create Account
  // Username field
  // is not exists만 하면 정확히 어디에 없는지 모르기에 정확히 어디에 없는지 명시하는게 좋을듯
  USERNAME_IS_NOT_EXISTS = 'USERNAME_IS_NOT_EXISTS',
  USERNAME_CAN_ONLY_BE_A_STRING = 'USERNAME_CAN_ONLY_BE_A_STRING',
  // Nickname field
  INVALID_NICKNAME = 'INVALID_NICKNAME',
  NICKNAME_IS_NOT_EXISTS = 'NICKNAME_IS_NOT_EXISTS',
  NICKNAME_CAN_ONLY_BE_A_STRING = 'NICKNAME_CAN_ONLY_BE_A_STRING',
  // Email field
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  EMAIL_IS_NOT_VALIDATE = 'EMAIL_IS_NOT_VALIDATE',
  EMAIL_IS_NOT_EXISTS = 'EMAIL_IS_NOT_EXISTS',
  EMAIL_CAN_ONLY_BE_A_STRING = 'EMAIL_CAN_ONLY_BE_A_STRING',
  // Password field
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  PASSWORD_IS_SHORT = 'PASSWORD_IS_SHORT',
  PASSWORD_IS_NOT_EXISTS = 'PASSWORD_IS_NOT_EXISTS',
  PASSWORD_CAN_ONLY_BE_A_STRING = 'PASSWORD_CAN_ONLY_BE_A_STRING',

  // Find User
  // Id field
  ID_IS_NOT_EXISTS = 'ID_IS_NOT_EXISTS',
  ID_CAN_ONLY_BE_A_STRING = 'ID_CAN_ONLY_BE_A_STRING',
}
