version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace/tumtum-monorepo:cached
    command: sleep infinity
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tumtum_dev
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tumtum_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
